// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.mirson.grpc.lib;

public final class StockServiceProto {
  private StockServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockServiceReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockServiceReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022StockService.proto\"#\n\023StockServiceRequ" +
      "est\022\014\n\004name\030\001 \001(\t\"$\n\021StockServiceReply\022\017" +
      "\n\007message\030\001 \001(\t2K\n\014StockService\022;\n\rGetSt" +
      "ockPrice\022\024.StockServiceRequest\032\022.StockSe" +
      "rviceReply\"\000B*\n\023com.mirson.grpc.libB\021Sto" +
      "ckServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StockServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockServiceRequest_descriptor,
        new String[] { "Name", });
    internal_static_StockServiceReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StockServiceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockServiceReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
