// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

/**
 * Protobuf type {@code surfaceDataSelect.RetArr2D}
 */
public  final class RetArr2D extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:surfaceDataSelect.RetArr2D)
    RetArr2DOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetArr2D.newBuilder() to construct.
  private RetArr2D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetArr2D() {
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RetArr2D(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rowCount_ = input.readInt32();
            break;
          }
          case 16: {

            colCount_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              data_ = new java.util.ArrayList<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow>();
              mutable_bitField0_ |= 0x00000004;
            }
            data_.add(
                input.readMessage(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_RetArr2D_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_RetArr2D_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.class, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.Builder.class);
  }

  private int bitField0_;
  public static final int ROWCOUNT_FIELD_NUMBER = 1;
  private int rowCount_;
  /**
   * <code>int32 rowCount = 1;</code>
   */
  public int getRowCount() {
    return rowCount_;
  }

  public static final int COLCOUNT_FIELD_NUMBER = 2;
  private int colCount_;
  /**
   * <code>int32 colCount = 2;</code>
   */
  public int getColCount() {
    return colCount_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow> data_;
  /**
   * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
   */
  public java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
   */
  public java.util.List<? extends com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
   */
  public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
   */
  public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rowCount_ != 0) {
      output.writeInt32(1, rowCount_);
    }
    if (colCount_ != 0) {
      output.writeInt32(2, colCount_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(3, data_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rowCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rowCount_);
    }
    if (colCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, colCount_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, data_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D)) {
      return super.equals(obj);
    }
    com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D other = (com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D) obj;

    if (getRowCount()
        != other.getRowCount()) return false;
    if (getColCount()
        != other.getColCount()) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRowCount();
    hash = (37 * hash) + COLCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getColCount();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code surfaceDataSelect.RetArr2D}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:surfaceDataSelect.RetArr2D)
      com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_RetArr2D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_RetArr2D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.class, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.Builder.class);
    }

    // Construct using com.rihang.surface.grpc.surfaceSelect.RetArr2D.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rowCount_ = 0;

      colCount_ = 0;

      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        dataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_RetArr2D_descriptor;
    }

    @java.lang.Override
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D getDefaultInstanceForType() {
      return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.getDefaultInstance();
    }

    @java.lang.Override
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D build() {
      com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D buildPartial() {
      com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D result = new com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.rowCount_ = rowCount_;
      result.colCount_ = colCount_;
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D) {
        return mergeFrom((com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D other) {
      if (other == com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D.getDefaultInstance()) return this;
      if (other.getRowCount() != 0) {
        setRowCount(other.getRowCount());
      }
      if (other.getColCount() != 0) {
        setColCount(other.getColCount());
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rowCount_ ;
    /**
     * <code>int32 rowCount = 1;</code>
     */
    public int getRowCount() {
      return rowCount_;
    }
    /**
     * <code>int32 rowCount = 1;</code>
     */
    public Builder setRowCount(int value) {
      
      rowCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rowCount = 1;</code>
     */
    public Builder clearRowCount() {
      
      rowCount_ = 0;
      onChanged();
      return this;
    }

    private int colCount_ ;
    /**
     * <code>int32 colCount = 2;</code>
     */
    public int getColCount() {
      return colCount_;
    }
    /**
     * <code>int32 colCount = 2;</code>
     */
    public Builder setColCount(int value) {
      
      colCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colCount = 2;</code>
     */
    public Builder clearColCount() {
      
      colCount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        data_ = new java.util.ArrayList<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow>(data_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder> dataBuilder_;

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder setData(
        int index, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder setData(
        int index, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder addData(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder addData(
        int index, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder addData(
        com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder addData(
        int index, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public java.util.List<? extends com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.getDefaultInstance());
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.getDefaultInstance());
    }
    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    public java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow.Builder, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder>(
                data_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:surfaceDataSelect.RetArr2D)
  }

  // @@protoc_insertion_point(class_scope:surfaceDataSelect.RetArr2D)
  private static final com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D();
  }

  public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetArr2D>
      PARSER = new com.google.protobuf.AbstractParser<RetArr2D>() {
    @java.lang.Override
    public RetArr2D parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RetArr2D(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RetArr2D> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetArr2D> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2D getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

