// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public interface RetArr2DRowOrBuilder extends
        // @@protoc_insertion_point(interface_extends:surfaceDataSelect.RetArr2DRow)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string row = 1;</code>
     */
    java.util.List<java.lang.String>
    getRowList();

    /**
     * <code>repeated string row = 1;</code>
     */
    int getRowCount();

    /**
     * <code>repeated string row = 1;</code>
     */
    java.lang.String getRow(int index);

    /**
     * <code>repeated string row = 1;</code>
     */
    com.google.protobuf.ByteString
    getRowBytes(int index);
}
