// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public interface RetArr2DOrBuilder extends
        // @@protoc_insertion_point(interface_extends:surfaceDataSelect.RetArr2D)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rowCount = 1;</code>
     */
    int getRowCount();

    /**
     * <code>int32 colCount = 2;</code>
     */
    int getColCount();

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    java.util.List<com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow>
    getDataList();

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRow getData(int index);

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    int getDataCount();

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    java.util.List<? extends com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder>
    getDataOrBuilderList();

    /**
     * <code>repeated .surfaceDataSelect.RetArr2DRow data = 3;</code>
     */
    com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.RetArr2DRowOrBuilder getDataOrBuilder(
            int index);
}
