// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public final class SelectProto {
  private SelectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetStationProByValidTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetStationProByValidTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleInRectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleInRectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleByStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleByStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleInRegionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleInRegionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfEleInBasinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfEleInBasinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreInRectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreInRectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreByStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreByStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreInRegionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreInRegionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfPreInBasinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfPreInBasinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemInRectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemInRectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemByStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemByStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemInRegionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemInRegionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemInBasinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemInBasinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmInRectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmInRectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmInRegionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmInRegionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemFtmInBasinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemFtmInBasinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_GetSurfEleByTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_GetSurfEleByTimeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_RetArr2DRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_RetArr2DRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_surfaceDataSelect_RetArr2D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_surfaceDataSelect_RetArr2D_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsurface.proto\022\021surfaceDataSelect\"\205\001\n$G" +
      "etStationProByValidTimeRangeRequest\022\016\n\006s" +
      "tdIds\030\001 \001(\t\022\021\n\tmaketimes\030\002 \001(\t\022\024\n\014startY" +
      "btimes\030\003 \001(\t\022\022\n\nendYbtimes\030\004 \001(\t\022\020\n\010data" +
      "Code\030\005 \001(\t\"\247\002\n\027GetSurfEleByTimeRequest\022\020" +
      "\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\026\n\016el" +
      "eValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030\004 \001(\t\022\017\n\007" +
      "orderBy\030\005 \001(\t\022\r\n\005times\030\006 \001(\t\022\023\n\013minSepar" +
      "ate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t\022\016\n\006minLo" +
      "n\030\t \001(\t\022\016\n\006maxLon\030\n \001(\t\022\016\n\006minLat\030\013 \001(\t\022" +
      "\016\n\006maxLat\030\014 \001(\t\022\021\n\tstaLevels\030\r \001(\t\022\017\n\007ct" +
      "Level\030\016 \001(\t\022\017\n\007crLabel\030\017 \001(\t\"\255\002\n\035GetSurf" +
      "EleInRectByTimeRequest\022\020\n\010dataCode\030\001 \001(\t" +
      "\022\020\n\010elements\030\002 \001(\t\022\026\n\016eleValueRanges\030\003 \001" +
      "(\t\022\020\n\010limitCnt\030\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\r\n" +
      "\005times\030\006 \001(\t\022\023\n\013minSeparate\030\007 \001(\t\022\024\n\014hou" +
      "rSeparate\030\010 \001(\t\022\016\n\006minLon\030\t \001(\t\022\016\n\006maxLo" +
      "n\030\n \001(\t\022\016\n\006minLat\030\013 \001(\t\022\016\n\006maxLat\030\014 \001(\t\022" +
      "\021\n\tstaLevels\030\r \001(\t\022\017\n\007ctLevel\030\016 \001(\t\022\017\n\007c" +
      "rLabel\030\017 \001(\t\"\335\001\n\037GetSurfEleByTimeAndStaI" +
      "DRequest\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002" +
      " \001(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt" +
      "\030\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\r\n\005times\030\006 \001(\t\022\023" +
      "\n\013minSeparate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(" +
      "\t\022\021\n\tstaLevels\030\t \001(\t\022\016\n\006staIds\030\n \001(\t\"\366\001\n" +
      "$GetSurfEleByTimeAndStaIDRangeRequest\022\020\n" +
      "\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\026\n\016ele" +
      "ValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030\004 \001(\t\022\017\n\007o" +
      "rderBy\030\005 \001(\t\022\r\n\005times\030\006 \001(\t\022\023\n\013minSepara" +
      "te\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t\022\020\n\010minSta" +
      "Id\030\t \001(\t\022\020\n\010maxStaId\030\n \001(\t\022\021\n\tstaLevels\030" +
      "\013 \001(\t\"\364\001\n\037GetSurfEleInRegionByTimeReques" +
      "t\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\026\n" +
      "\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030\004 \001(\t\022" +
      "\017\n\007orderBy\030\005 \001(\t\022\r\n\005times\030\006 \001(\t\022\023\n\013minSe" +
      "parate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t\022\021\n\tst" +
      "aLevels\030\t \001(\t\022\022\n\nadminCodes\030\n \001(\t\022\021\n\ttow" +
      "nCodes\030\013 \001(\t\"\340\001\n\036GetSurfEleInBasinByTime" +
      "Request\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 " +
      "\001(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030" +
      "\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\r\n\005times\030\006 \001(\t\022\023\n" +
      "\013minSeparate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t" +
      "\022\021\n\tstaLevels\030\t \001(\t\022\022\n\nbasinCodes\030\n \001(\t\"" +
      "\316\001\n\034GetSurfEleByTimeRangeRequest\022\020\n\010data" +
      "Code\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\026\n\016eleValue" +
      "Ranges\030\003 \001(\t\022\020\n\010limitCnt\030\004 \001(\t\022\017\n\007orderB" +
      "y\030\005 \001(\t\022\021\n\ttimeRange\030\006 \001(\t\022\023\n\013minSeparat" +
      "e\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t\022\021\n\tstaLeve" +
      "ls\030\t \001(\t\"\224\002\n\"GetSurfEleInRectByTimeRange" +
      "Request\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 " +
      "\001(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030" +
      "\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\021\n\ttimeRange\030\006 \001(" +
      "\t\022\023\n\013minSeparate\030\007 \001(\t\022\024\n\014hourSeparate\030\010" +
      " \001(\t\022\016\n\006minLon\030\t \001(\t\022\016\n\006maxLon\030\n \001(\t\022\016\n\006" +
      "minLat\030\013 \001(\t\022\016\n\006maxLat\030\014 \001(\t\022\021\n\tstaLevel" +
      "s\030\r \001(\t\"\346\001\n$GetSurfEleByTimeRangeAndStaI" +
      "DRequest\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002" +
      " \001(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt" +
      "\030\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\021\n\ttimeRange\030\006 \001" +
      "(\t\022\023\n\013minSeparate\030\007 \001(\t\022\024\n\014hourSeparate\030" +
      "\010 \001(\t\022\021\n\tstaLevels\030\t \001(\t\022\016\n\006staIds\030\n \001(\t" +
      "\"\377\001\n)GetSurfEleByTimeRangeAndStaIDRangeR" +
      "equest\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010elements\030\002 \001" +
      "(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022\020\n\010limitCnt\030\004" +
      " \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\021\n\ttimeRange\030\006 \001(\t" +
      "\022\023\n\013minSeparate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 " +
      "\001(\t\022\020\n\010minStaId\030\t \001(\t\022\020\n\010maxStaId\030\n \001(\t\022" +
      "\021\n\tstaLevels\030\013 \001(\t\"\375\001\n$GetSurfEleInRegio" +
      "nByTimeRangeRequest\022\020\n\010dataCode\030\001 \001(\t\022\020\n" +
      "\010elements\030\002 \001(\t\022\026\n\016eleValueRanges\030\003 \001(\t\022" +
      "\020\n\010limitCnt\030\004 \001(\t\022\017\n\007orderBy\030\005 \001(\t\022\021\n\tti" +
      "meRange\030\006 \001(\t\022\023\n\013minSeparate\030\007 \001(\t\022\024\n\014ho" +
      "urSeparate\030\010 \001(\t\022\021\n\tstaLevels\030\t \001(\t\022\022\n\na" +
      "dminCodes\030\n \001(\t\022\021\n\ttownCodes\030\013 \001(\t\"\351\001\n#G" +
      "etSurfEleInBasinByTimeRangeRequest\022\020\n\010da" +
      "taCode\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\026\n\016eleVal" +
      "ueRanges\030\003 \001(\t\022\020\n\010limitCnt\030\004 \001(\t\022\017\n\007orde" +
      "rBy\030\005 \001(\t\022\021\n\ttimeRange\030\006 \001(\t\022\023\n\013minSepar" +
      "ate\030\007 \001(\t\022\024\n\014hourSeparate\030\010 \001(\t\022\021\n\tstaLe" +
      "vels\030\t \001(\t\022\022\n\nbasinCodes\030\n \001(\t\"\362\001\n\022StatS" +
      "urfEleRequest\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010eleme" +
      "nts\030\002 \001(\t\022\020\n\010statEles\030\003 \001(\t\022\026\n\016eleValueR" +
      "anges\030\004 \001(\t\022\032\n\022statEleValueRanges\030\005 \001(\t\022" +
      "\020\n\010limitCnt\030\006 \001(\t\022\017\n\007orderBy\030\007 \001(\t\022\021\n\tti" +
      "meRange\030\010 \001(\t\022\023\n\013minSeparate\030\t \001(\t\022\024\n\014ho" +
      "urSeparate\030\n \001(\t\022\021\n\tstaLevels\030\013 \001(\t\"\270\002\n\030" +
      "StatSurfEleInRectRequest\022\020\n\010dataCode\030\001 \001" +
      "(\t\022\020\n\010elements\030\002 \001(\t\022\020\n\010statEles\030\003 \001(\t\022\026" +
      "\n\016eleValueRanges\030\004 \001(\t\022\032\n\022statEleValueRa" +
      "nges\030\005 \001(\t\022\020\n\010limitCnt\030\006 \001(\t\022\017\n\007orderBy\030" +
      "\007 \001(\t\022\021\n\ttimeRange\030\010 \001(\t\022\023\n\013minSeparate\030" +
      "\t \001(\t\022\024\n\014hourSeparate\030\n \001(\t\022\016\n\006minLon\030\013 " +
      "\001(\t\022\016\n\006maxLon\030\014 \001(\t\022\016\n\006minLat\030\r \001(\t\022\016\n\006m" +
      "axLat\030\016 \001(\t\022\021\n\tstaLevels\030\017 \001(\t\"\211\002\n\031StatS" +
      "urfEleByStaIDRequest\022\020\n\010dataCode\030\001 \001(\t\022\020" +
      "\n\010elements\030\002 \001(\t\022\020\n\010statEles\030\003 \001(\t\022\026\n\016el" +
      "eValueRanges\030\004 \001(\t\022\032\n\022statEleValueRanges" +
      "\030\005 \001(\t\022\020\n\010limitCnt\030\006 \001(\t\022\017\n\007orderBy\030\007 \001(" +
      "\t\022\021\n\ttimeRange\030\010 \001(\t\022\023\n\013minSeparate\030\t \001(" +
      "\t\022\024\n\014hourSeparate\030\n \001(\t\022\016\n\006staIds\030\013 \001(\t\022" +
      "\021\n\tstaLevels\030\014 \001(\t\"\242\002\n\036StatSurfEleByStaI" +
      "DRangeRequest\022\020\n\010dataCode\030\001 \001(\t\022\020\n\010eleme" +
      "nts\030\002 \001(\t\022\020\n\010statEles\030\003 \001(\t\022\026\n\016eleValueR" +
      "anges\030\004 \001(\t\022\032\n\022statEleValueRanges\030\005 \001(\t\022" +
      "\020\n\010limitCnt\030\006 \001(\t\022\017\n\007orderBy\030\007 \001(\t\022\021\n\tti" +
      "meRange\030\010 \001(\t\022\023\n\013minSeparate\030\t \001(\t\022\024\n\014ho" +
      "urSeparate\030\n \001(\t\022\020\n\010minStaId\030\013 \001(\t\022\020\n\010ma" +
      "xStaId\030\014 \001(\t\022\021\n\tstaLevels\030\r \001(\t\"\241\002\n\032Stat" +
      "SurfEleInRegionRequest\022\020\n\010dataCode\030\001 \001(\t" +
      "\022\020\n\010elements\030\002 \001(\t\022\020\n\010statEles\030\003 \001(\t\022\026\n\016" +
      "eleValueRanges\030\004 \001(\t\022\032\n\022statEleValueRang" +
      "es\030\005 \001(\t\022\020\n\010limitCnt\030\006 \001(\t\022\017\n\007orderBy\030\007 " +
      "\001(\t\022\021\n\ttimeRange\030\010 \001(\t\022\023\n\013minSeparate\030\t " +
      "\001(\t\022\024\n\014hourSeparate\030\n \001(\t\022\021\n\tstaLevels\030\013" +
      " \001(\t\022\022\n\nadminCodes\030\014 \001(\t\022\021\n\ttownCodes\030\r " +
      "\001(\t\"\215\002\n\031StatSurfEleInBasinRequest\022\020\n\010dat" +
      "aCode\030\001 \001(\t\022\020\n\010elements\030\002 \001(\t\022\020\n\010statEle" +
      "s\030\003 \001(\t\022\026\n\016eleValueRanges\030\004 \001(\t\022\032\n\022statE" +
      "leValueRanges\030\005 \001(\t\022\020\n\010limitCnt\030\006 \001(\t\022\017\n" +
      "\007orderBy\030\007 \001(\t\022\021\n\ttimeRange\030\010 \001(\t\022\023\n\013min" +
      "Separate\030\t \001(\t\022\024\n\014hourSeparate\030\n \001(\t\022\021\n\t" +
      "staLevels\030\013 \001(\t\022\022\n\nbasinCodes\030\014 \001(\t\"\335\001\n\022" +
      "StatSurfPreRequest\022\020\n\010elements\030\001 \001(\t\022\032\n\022" +
      "statEleValueRanges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001" +
      "(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\016" +
      "\n\006minLon\030\006 \001(\t\022\016\n\006maxLon\030\007 \001(\t\022\016\n\006minLat" +
      "\030\010 \001(\t\022\016\n\006maxLat\030\t \001(\t\022\021\n\tstaLevels\030\n \001(" +
      "\t\022\020\n\010dataCode\030\013 \001(\t\"\343\001\n\030StatSurfPreInRec" +
      "tRequest\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEleVal" +
      "ueRanges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orde" +
      "rBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\016\n\006minLon\030\006" +
      " \001(\t\022\016\n\006maxLon\030\007 \001(\t\022\016\n\006minLat\030\010 \001(\t\022\016\n\006" +
      "maxLat\030\t \001(\t\022\021\n\tstaLevels\030\n \001(\t\022\020\n\010dataC" +
      "ode\030\013 \001(\t\"\264\001\n\031StatSurfPreByStaIDRequest\022" +
      "\020\n\010elements\030\001 \001(\t\022\032\n\022statEleValueRanges\030" +
      "\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t" +
      "\022\021\n\ttimeRange\030\005 \001(\t\022\016\n\006staIds\030\006 \001(\t\022\021\n\ts" +
      "taLevels\030\007 \001(\t\022\020\n\010dataCode\030\010 \001(\t\"\315\001\n\036Sta" +
      "tSurfPreByStaIDRangeRequest\022\020\n\010elements\030" +
      "\001 \001(\t\022\032\n\022statEleValueRanges\030\002 \001(\t\022\020\n\010lim" +
      "itCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRang" +
      "e\030\005 \001(\t\022\020\n\010minStaId\030\006 \001(\t\022\020\n\010maxStaId\030\007 " +
      "\001(\t\022\021\n\tstaLevels\030\010 \001(\t\022\020\n\010dataCode\030\t \001(\t" +
      "\"\314\001\n\032StatSurfPreInRegionRequest\022\020\n\010eleme" +
      "nts\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002 \001(\t\022\020\n" +
      "\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttime" +
      "Range\030\005 \001(\t\022\021\n\tstaLevels\030\006 \001(\t\022\022\n\nadminC" +
      "odes\030\007 \001(\t\022\021\n\ttownCodes\030\010 \001(\t\022\020\n\010dataCod" +
      "e\030\t \001(\t\"\270\001\n\031StatSurfPreInBasinRequest\022\020\n" +
      "\010elements\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002 " +
      "\001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021" +
      "\n\ttimeRange\030\005 \001(\t\022\021\n\tstaLevels\030\006 \001(\t\022\022\n\n" +
      "basinCodes\030\007 \001(\t\022\020\n\010dataCode\030\010 \001(\t\"\235\001\n\022S" +
      "tatSurfTemRequest\022\020\n\010elements\030\001 \001(\t\022\032\n\022s" +
      "tatEleValueRanges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(" +
      "\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\021\n" +
      "\tstaLevels\030\006 \001(\t\022\020\n\010dataCode\030\007 \001(\t\"\343\001\n\030S" +
      "tatSurfTemInRectRequest\022\020\n\010elements\030\001 \001(" +
      "\t\022\032\n\022statEleValueRanges\030\002 \001(\t\022\020\n\010limitCn" +
      "t\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 " +
      "\001(\t\022\016\n\006minLon\030\006 \001(\t\022\016\n\006maxLon\030\007 \001(\t\022\016\n\006m" +
      "inLat\030\010 \001(\t\022\016\n\006maxLat\030\t \001(\t\022\021\n\tstaLevels" +
      "\030\n \001(\t\022\020\n\010dataCode\030\013 \001(\t\"\264\001\n\031StatSurfTem" +
      "ByStaIDRequest\022\020\n\010elements\030\001 \001(\t\022\032\n\022stat" +
      "EleValueRanges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017" +
      "\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\016\n\006st" +
      "aIds\030\006 \001(\t\022\021\n\tstaLevels\030\007 \001(\t\022\020\n\010dataCod" +
      "e\030\010 \001(\t\"\315\001\n\036StatSurfTemByStaIDRangeReque" +
      "st\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEleValueRang" +
      "es\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 " +
      "\001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\020\n\010minStaId\030\006 \001(\t" +
      "\022\020\n\010maxStaId\030\007 \001(\t\022\021\n\tstaLevels\030\010 \001(\t\022\020\n" +
      "\010dataCode\030\t \001(\t\"\314\001\n\032StatSurfTemInRegionR" +
      "equest\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEleValue" +
      "Ranges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderB" +
      "y\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\021\n\tstaLevels\030" +
      "\006 \001(\t\022\022\n\nadminCodes\030\007 \001(\t\022\021\n\ttownCodes\030\010" +
      " \001(\t\022\020\n\010dataCode\030\t \001(\t\"\270\001\n\031StatSurfTemIn" +
      "BasinRequest\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEl" +
      "eValueRanges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007" +
      "orderBy\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\021\n\tstaL" +
      "evels\030\006 \001(\t\022\022\n\nbasinCodes\030\007 \001(\t\022\020\n\010dataC" +
      "ode\030\010 \001(\t\"\240\001\n\025StatSurfTemFtmRequest\022\020\n\010e" +
      "lements\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002 \001(" +
      "\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\t" +
      "timeRange\030\005 \001(\t\022\021\n\tstaLevels\030\006 \001(\t\022\020\n\010da" +
      "taCode\030\007 \001(\t\"\346\001\n\033StatSurfTemFtmInRectReq" +
      "uest\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEleValueRa" +
      "nges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030" +
      "\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\016\n\006minLon\030\006 \001(\t" +
      "\022\016\n\006maxLon\030\007 \001(\t\022\016\n\006minLat\030\010 \001(\t\022\016\n\006maxL" +
      "at\030\t \001(\t\022\021\n\tstaLevels\030\n \001(\t\022\020\n\010dataCode\030" +
      "\013 \001(\t\"\267\001\n\034StatSurfTemFtmByStaIDRequest\022\020" +
      "\n\010elements\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002" +
      " \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022" +
      "\021\n\ttimeRange\030\005 \001(\t\022\016\n\006staIds\030\006 \001(\t\022\021\n\tst" +
      "aLevels\030\007 \001(\t\022\020\n\010dataCode\030\010 \001(\t\"\320\001\n!Stat" +
      "SurfTemFtmByStaIDRangeRequest\022\020\n\010element" +
      "s\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002 \001(\t\022\020\n\010l" +
      "imitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n\ttimeRa" +
      "nge\030\005 \001(\t\022\020\n\010minStaId\030\006 \001(\t\022\020\n\010maxStaId\030" +
      "\007 \001(\t\022\021\n\tstaLevels\030\010 \001(\t\022\020\n\010dataCode\030\t \001" +
      "(\t\"\317\001\n\035StatSurfTemFtmInRegionRequest\022\020\n\010" +
      "elements\030\001 \001(\t\022\032\n\022statEleValueRanges\030\002 \001" +
      "(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy\030\004 \001(\t\022\021\n" +
      "\ttimeRange\030\005 \001(\t\022\021\n\tstaLevels\030\006 \001(\t\022\022\n\na" +
      "dminCodes\030\007 \001(\t\022\021\n\ttownCodes\030\010 \001(\t\022\020\n\010da" +
      "taCode\030\t \001(\t\"\273\001\n\034StatSurfTemFtmInBasinRe" +
      "quest\022\020\n\010elements\030\001 \001(\t\022\032\n\022statEleValueR" +
      "anges\030\002 \001(\t\022\020\n\010limitCnt\030\003 \001(\t\022\017\n\007orderBy" +
      "\030\004 \001(\t\022\021\n\ttimeRange\030\005 \001(\t\022\021\n\tstaLevels\030\006" +
      " \001(\t\022\022\n\nbasinCodes\030\007 \001(\t\022\020\n\010dataCode\030\010 \001" +
      "(\t\"~\n\031StatSurfTemByMYearRequest\022\020\n\010eleme" +
      "nts\030\001 \001(\t\022\r\n\005minMD\030\002 \001(\t\022\r\n\005maxMD\030\003 \001(\t\022" +
      "\017\n\007minYear\030\004 \001(\t\022\016\n\006staIds\030\005 \001(\t\022\020\n\010data" +
      "Code\030\006 \001(\t\"b\n\030GetSurfEleByTimeResponse\022\016" +
      "\n\006status\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022)\n\004data\030\003 \001(" +
      "\0132\033.surfaceDataSelect.RetArr2D\"\032\n\013RetArr" +
      "2DRow\022\013\n\003row\030\001 \003(\t\"\\\n\010RetArr2D\022\020\n\010rowCou" +
      "nt\030\001 \001(\005\022\020\n\010colCount\030\002 \001(\005\022,\n\004data\030\003 \003(\013" +
      "2\036.surfaceDataSelect.RetArr2DRow2\213$\n\021Sur" +
      "faceDataSelect\022\207\001\n\035GetStationProByValidT" +
      "imeRange\0227.surfaceDataSelect.GetStationP" +
      "roByValidTimeRangeRequest\032+.surfaceDataS" +
      "elect.GetSurfEleByTimeResponse\"\000\022m\n\020GetS" +
      "urfEleByTime\022*.surfaceDataSelect.GetSurf" +
      "EleByTimeRequest\032+.surfaceDataSelect.Get" +
      "SurfEleByTimeResponse\"\000\022y\n\026GetSurfEleInR" +
      "ectByTime\0220.surfaceDataSelect.GetSurfEle" +
      "InRectByTimeRequest\032+.surfaceDataSelect." +
      "GetSurfEleByTimeResponse\"\000\022}\n\030GetSurfEle" +
      "ByTimeAndStaID\0222.surfaceDataSelect.GetSu" +
      "rfEleByTimeAndStaIDRequest\032+.surfaceData" +
      "Select.GetSurfEleByTimeResponse\"\000\022\207\001\n\035Ge" +
      "tSurfEleByTimeAndStaIDRange\0227.surfaceDat" +
      "aSelect.GetSurfEleByTimeAndStaIDRangeReq" +
      "uest\032+.surfaceDataSelect.GetSurfEleByTim" +
      "eResponse\"\000\022}\n\030GetSurfEleInRegionByTime\022" +
      "2.surfaceDataSelect.GetSurfEleInRegionBy" +
      "TimeRequest\032+.surfaceDataSelect.GetSurfE" +
      "leByTimeResponse\"\000\022{\n\027GetSurfEleInBasinB" +
      "yTime\0221.surfaceDataSelect.GetSurfEleInBa" +
      "sinByTimeRequest\032+.surfaceDataSelect.Get" +
      "SurfEleByTimeResponse\"\000\022w\n\025GetSurfEleByT" +
      "imeRange\022/.surfaceDataSelect.GetSurfEleB" +
      "yTimeRangeRequest\032+.surfaceDataSelect.Ge" +
      "tSurfEleByTimeResponse\"\000\022\203\001\n\033GetSurfEleI" +
      "nRectByTimeRange\0225.surfaceDataSelect.Get" +
      "SurfEleInRectByTimeRangeRequest\032+.surfac" +
      "eDataSelect.GetSurfEleByTimeResponse\"\000\022\207" +
      "\001\n\035GetSurfEleByTimeRangeAndStaID\0227.surfa" +
      "ceDataSelect.GetSurfEleByTimeRangeAndSta" +
      "IDRequest\032+.surfaceDataSelect.GetSurfEle" +
      "ByTimeResponse\"\000\022\221\001\n\"GetSurfEleByTimeRan" +
      "geAndStaIDRange\022<.surfaceDataSelect.GetS" +
      "urfEleByTimeRangeAndStaIDRangeRequest\032+." +
      "surfaceDataSelect.GetSurfEleByTimeRespon" +
      "se\"\000\022\207\001\n\035GetSurfEleInRegionByTimeRange\0227" +
      ".surfaceDataSelect.GetSurfEleInRegionByT" +
      "imeRangeRequest\032+.surfaceDataSelect.GetS" +
      "urfEleByTimeResponse\"\000\022\205\001\n\034GetSurfEleInB" +
      "asinByTimeRange\0226.surfaceDataSelect.GetS" +
      "urfEleInBasinByTimeRangeRequest\032+.surfac" +
      "eDataSelect.GetSurfEleByTimeResponse\"\000\022c" +
      "\n\013StatSurfEle\022%.surfaceDataSelect.StatSu" +
      "rfEleRequest\032+.surfaceDataSelect.GetSurf" +
      "EleByTimeResponse\"\000\022o\n\021StatSurfEleInRect" +
      "\022+.surfaceDataSelect.StatSurfEleInRectRe" +
      "quest\032+.surfaceDataSelect.GetSurfEleByTi" +
      "meResponse\"\000\022q\n\022StatSurfEleByStaID\022,.sur" +
      "faceDataSelect.StatSurfEleByStaIDRequest" +
      "\032+.surfaceDataSelect.GetSurfEleByTimeRes" +
      "ponse\"\000\022{\n\027StatSurfEleByStaIDRange\0221.sur" +
      "faceDataSelect.StatSurfEleByStaIDRangeRe" +
      "quest\032+.surfaceDataSelect.GetSurfEleByTi" +
      "meResponse\"\000\022s\n\023StatSurfEleInRegion\022-.su" +
      "rfaceDataSelect.StatSurfEleInRegionReque" +
      "st\032+.surfaceDataSelect.GetSurfEleByTimeR" +
      "esponse\"\000\022q\n\022StatSurfEleInBasin\022,.surfac" +
      "eDataSelect.StatSurfEleInBasinRequest\032+." +
      "surfaceDataSelect.GetSurfEleByTimeRespon" +
      "se\"\000\022c\n\013StatSurfPre\022%.surfaceDataSelect." +
      "StatSurfPreRequest\032+.surfaceDataSelect.G" +
      "etSurfEleByTimeResponse\"\000\022o\n\021StatSurfPre" +
      "InRect\022+.surfaceDataSelect.StatSurfPreIn" +
      "RectRequest\032+.surfaceDataSelect.GetSurfE" +
      "leByTimeResponse\"\000\022q\n\022StatSurfPreByStaID" +
      "\022,.surfaceDataSelect.StatSurfPreByStaIDR" +
      "equest\032+.surfaceDataSelect.GetSurfEleByT" +
      "imeResponse\"\000\022{\n\027StatSurfPreByStaIDRange" +
      "\0221.surfaceDataSelect.StatSurfPreByStaIDR" +
      "angeRequest\032+.surfaceDataSelect.GetSurfE" +
      "leByTimeResponse\"\000\022s\n\023StatSurfPreInRegio" +
      "n\022-.surfaceDataSelect.StatSurfPreInRegio" +
      "nRequest\032+.surfaceDataSelect.GetSurfEleB" +
      "yTimeResponse\"\000\022q\n\022StatSurfPreInBasin\022,." +
      "surfaceDataSelect.StatSurfPreInBasinRequ" +
      "est\032+.surfaceDataSelect.GetSurfEleByTime" +
      "Response\"\000\022c\n\013StatSurfTem\022%.surfaceDataS" +
      "elect.StatSurfTemRequest\032+.surfaceDataSe" +
      "lect.GetSurfEleByTimeResponse\"\000\022o\n\021StatS" +
      "urfTemInRect\022+.surfaceDataSelect.StatSur" +
      "fTemInRectRequest\032+.surfaceDataSelect.Ge" +
      "tSurfEleByTimeResponse\"\000\022q\n\022StatSurfTemB" +
      "yStaID\022,.surfaceDataSelect.StatSurfTemBy" +
      "StaIDRequest\032+.surfaceDataSelect.GetSurf" +
      "EleByTimeResponse\"\000\022{\n\027StatSurfTemByStaI" +
      "DRange\0221.surfaceDataSelect.StatSurfTemBy" +
      "StaIDRangeRequest\032+.surfaceDataSelect.Ge" +
      "tSurfEleByTimeResponse\"\000\022s\n\023StatSurfTemI" +
      "nRegion\022-.surfaceDataSelect.StatSurfTemI" +
      "nRegionRequest\032+.surfaceDataSelect.GetSu" +
      "rfEleByTimeResponse\"\000\022q\n\022StatSurfTemInBa" +
      "sin\022,.surfaceDataSelect.StatSurfTemInBas" +
      "inRequest\032+.surfaceDataSelect.GetSurfEle" +
      "ByTimeResponse\"\000\022i\n\016StatSurfTemFtm\022(.sur" +
      "faceDataSelect.StatSurfTemFtmRequest\032+.s" +
      "urfaceDataSelect.GetSurfEleByTimeRespons" +
      "e\"\000\022u\n\024StatSurfTemFtmInRect\022..surfaceDat" +
      "aSelect.StatSurfTemFtmInRectRequest\032+.su" +
      "rfaceDataSelect.GetSurfEleByTimeResponse" +
      "\"\000\022w\n\025StatSurfTemFtmByStaID\022/.surfaceDat" +
      "aSelect.StatSurfTemFtmByStaIDRequest\032+.s" +
      "urfaceDataSelect.GetSurfEleByTimeRespons" +
      "e\"\000\022\201\001\n\032StatSurfTemFtmByStaIDRange\0224.sur" +
      "faceDataSelect.StatSurfTemFtmByStaIDRang" +
      "eRequest\032+.surfaceDataSelect.GetSurfEleB" +
      "yTimeResponse\"\000\022y\n\026StatSurfTemFtmInRegio" +
      "n\0220.surfaceDataSelect.StatSurfTemFtmInRe" +
      "gionRequest\032+.surfaceDataSelect.GetSurfE" +
      "leByTimeResponse\"\000\022w\n\025StatSurfTemFtmInBa" +
      "sin\022/.surfaceDataSelect.StatSurfTemFtmIn" +
      "BasinRequest\032+.surfaceDataSelect.GetSurf" +
      "EleByTimeResponse\"\000\022q\n\022StatSurfTemByMYea" +
      "r\022,.surfaceDataSelect.StatSurfTemByMYear" +
      "Request\032+.surfaceDataSelect.GetSurfEleBy" +
      "TimeResponse\"\000BJ\n%com.rihang.surface.grp" +
      "c.surfaceSelectB\013SelectProtoP\001\242\002\021Surface" +
      "DataSelectb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_surfaceDataSelect_GetStationProByValidTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_surfaceDataSelect_GetStationProByValidTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetStationProByValidTimeRangeRequest_descriptor,
        new java.lang.String[] { "StdIds", "Maketimes", "StartYbtimes", "EndYbtimes", "DataCode", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_surfaceDataSelect_GetSurfEleByTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "CtLevel", "CrLabel", });
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "CtLevel", "CrLabel", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "StaLevels", "StaIds", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeAndStaIDRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "MinStaId", "MaxStaId", "StaLevels", });
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "StaLevels", "AdminCodes", "TownCodes", });
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "Times", "MinSeparate", "HourSeparate", "StaLevels", "BasinCodes", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", });
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInRectByTimeRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", "StaIds", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeRangeAndStaIDRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "MinStaId", "MaxStaId", "StaLevels", });
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInRegionByTimeRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", "AdminCodes", "TownCodes", });
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleInBasinByTimeRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "EleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", "BasinCodes", });
    internal_static_surfaceDataSelect_StatSurfEleRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_surfaceDataSelect_StatSurfEleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", });
    internal_static_surfaceDataSelect_StatSurfEleInRectRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_surfaceDataSelect_StatSurfEleInRectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleInRectRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", });
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleByStaIDRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaIds", "StaLevels", });
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_surfaceDataSelect_StatSurfEleByStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleByStaIDRangeRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "MinStaId", "MaxStaId", "StaLevels", });
    internal_static_surfaceDataSelect_StatSurfEleInRegionRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_surfaceDataSelect_StatSurfEleInRegionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleInRegionRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", "AdminCodes", "TownCodes", });
    internal_static_surfaceDataSelect_StatSurfEleInBasinRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_surfaceDataSelect_StatSurfEleInBasinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfEleInBasinRequest_descriptor,
        new java.lang.String[] { "DataCode", "Elements", "StatEles", "EleValueRanges", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinSeparate", "HourSeparate", "StaLevels", "BasinCodes", });
    internal_static_surfaceDataSelect_StatSurfPreRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_surfaceDataSelect_StatSurfPreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfPreInRectRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_surfaceDataSelect_StatSurfPreInRectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreInRectRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreByStaIDRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaIds", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_surfaceDataSelect_StatSurfPreByStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreByStaIDRangeRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinStaId", "MaxStaId", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfPreInRegionRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_surfaceDataSelect_StatSurfPreInRegionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreInRegionRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "AdminCodes", "TownCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfPreInBasinRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_surfaceDataSelect_StatSurfPreInBasinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfPreInBasinRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "BasinCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_surfaceDataSelect_StatSurfTemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemInRectRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_surfaceDataSelect_StatSurfTemInRectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemInRectRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemByStaIDRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaIds", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_surfaceDataSelect_StatSurfTemByStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemByStaIDRangeRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinStaId", "MaxStaId", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemInRegionRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_surfaceDataSelect_StatSurfTemInRegionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemInRegionRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "AdminCodes", "TownCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemInBasinRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_surfaceDataSelect_StatSurfTemInBasinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemInBasinRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "BasinCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_surfaceDataSelect_StatSurfTemFtmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmInRectRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_surfaceDataSelect_StatSurfTemFtmInRectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmInRectRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinLon", "MaxLon", "MinLat", "MaxLat", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaIds", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmByStaIDRangeRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "MinStaId", "MaxStaId", "StaLevels", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmInRegionRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_surfaceDataSelect_StatSurfTemFtmInRegionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmInRegionRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "AdminCodes", "TownCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemFtmInBasinRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_surfaceDataSelect_StatSurfTemFtmInBasinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemFtmInBasinRequest_descriptor,
        new java.lang.String[] { "Elements", "StatEleValueRanges", "LimitCnt", "OrderBy", "TimeRange", "StaLevels", "BasinCodes", "DataCode", });
    internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor,
        new java.lang.String[] { "Elements", "MinMD", "MaxMD", "MinYear", "StaIds", "DataCode", });
    internal_static_surfaceDataSelect_GetSurfEleByTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_surfaceDataSelect_GetSurfEleByTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_GetSurfEleByTimeResponse_descriptor,
        new java.lang.String[] { "Status", "Msg", "Data", });
    internal_static_surfaceDataSelect_RetArr2DRow_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_surfaceDataSelect_RetArr2DRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_RetArr2DRow_descriptor,
        new java.lang.String[] { "Row", });
    internal_static_surfaceDataSelect_RetArr2D_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_surfaceDataSelect_RetArr2D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_surfaceDataSelect_RetArr2D_descriptor,
        new java.lang.String[] { "RowCount", "ColCount", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
