// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public interface StatSurfTemFtmInBasinRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:surfaceDataSelect.StatSurfTemFtmInBasinRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string elements = 1;</code>
     */
    java.lang.String getElements();

    /**
     * <code>string elements = 1;</code>
     */
    com.google.protobuf.ByteString
    getElementsBytes();

    /**
     * <code>string statEleValueRanges = 2;</code>
     */
    java.lang.String getStatEleValueRanges();

    /**
     * <code>string statEleValueRanges = 2;</code>
     */
    com.google.protobuf.ByteString
    getStatEleValueRangesBytes();

    /**
     * <code>string limitCnt = 3;</code>
     */
    java.lang.String getLimitCnt();

    /**
     * <code>string limitCnt = 3;</code>
     */
    com.google.protobuf.ByteString
    getLimitCntBytes();

    /**
     * <code>string orderBy = 4;</code>
     */
    java.lang.String getOrderBy();

    /**
     * <code>string orderBy = 4;</code>
     */
    com.google.protobuf.ByteString
    getOrderByBytes();

    /**
     * <code>string timeRange = 5;</code>
     */
    java.lang.String getTimeRange();

    /**
     * <code>string timeRange = 5;</code>
     */
    com.google.protobuf.ByteString
    getTimeRangeBytes();

    /**
     * <code>string staLevels = 6;</code>
     */
    java.lang.String getStaLevels();

    /**
     * <code>string staLevels = 6;</code>
     */
    com.google.protobuf.ByteString
    getStaLevelsBytes();

    /**
     * <code>string basinCodes = 7;</code>
     */
    java.lang.String getBasinCodes();

    /**
     * <code>string basinCodes = 7;</code>
     */
    com.google.protobuf.ByteString
    getBasinCodesBytes();

    /**
     * <code>string dataCode = 8;</code>
     */
    java.lang.String getDataCode();

    /**
     * <code>string dataCode = 8;</code>
     */
    com.google.protobuf.ByteString
    getDataCodeBytes();
}
