// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public interface StatSurfEleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:surfaceDataSelect.StatSurfEleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataCode = 1;</code>
   */
  java.lang.String getDataCode();
  /**
   * <code>string dataCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataCodeBytes();

  /**
   * <code>string elements = 2;</code>
   */
  java.lang.String getElements();
  /**
   * <code>string elements = 2;</code>
   */
  com.google.protobuf.ByteString
      getElementsBytes();

  /**
   * <code>string statEles = 3;</code>
   */
  java.lang.String getStatEles();
  /**
   * <code>string statEles = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatElesBytes();

  /**
   * <code>string eleValueRanges = 4;</code>
   */
  java.lang.String getEleValueRanges();
  /**
   * <code>string eleValueRanges = 4;</code>
   */
  com.google.protobuf.ByteString
      getEleValueRangesBytes();

  /**
   * <code>string statEleValueRanges = 5;</code>
   */
  java.lang.String getStatEleValueRanges();
  /**
   * <code>string statEleValueRanges = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatEleValueRangesBytes();

  /**
   * <code>string limitCnt = 6;</code>
   */
  java.lang.String getLimitCnt();
  /**
   * <code>string limitCnt = 6;</code>
   */
  com.google.protobuf.ByteString
      getLimitCntBytes();

  /**
   * <code>string orderBy = 7;</code>
   */
  java.lang.String getOrderBy();
  /**
   * <code>string orderBy = 7;</code>
   */
  com.google.protobuf.ByteString
      getOrderByBytes();

  /**
   * <code>string timeRange = 8;</code>
   */
  java.lang.String getTimeRange();
  /**
   * <code>string timeRange = 8;</code>
   */
  com.google.protobuf.ByteString
      getTimeRangeBytes();

  /**
   * <code>string minSeparate = 9;</code>
   */
  java.lang.String getMinSeparate();
  /**
   * <code>string minSeparate = 9;</code>
   */
  com.google.protobuf.ByteString
      getMinSeparateBytes();

  /**
   * <code>string hourSeparate = 10;</code>
   */
  java.lang.String getHourSeparate();
  /**
   * <code>string hourSeparate = 10;</code>
   */
  com.google.protobuf.ByteString
      getHourSeparateBytes();

  /**
   * <code>string staLevels = 11;</code>
   */
  java.lang.String getStaLevels();
  /**
   * <code>string staLevels = 11;</code>
   */
  com.google.protobuf.ByteString
      getStaLevelsBytes();
}
