// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

public interface StatSurfTemByMYearRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:surfaceDataSelect.StatSurfTemByMYearRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string elements = 1;</code>
   */
  java.lang.String getElements();
  /**
   * <code>string elements = 1;</code>
   */
  com.google.protobuf.ByteString
      getElementsBytes();

  /**
   * <code>string minMD = 2;</code>
   */
  java.lang.String getMinMD();
  /**
   * <code>string minMD = 2;</code>
   */
  com.google.protobuf.ByteString
      getMinMDBytes();

  /**
   * <code>string maxMD = 3;</code>
   */
  java.lang.String getMaxMD();
  /**
   * <code>string maxMD = 3;</code>
   */
  com.google.protobuf.ByteString
      getMaxMDBytes();

  /**
   * <code>string minYear = 4;</code>
   */
  java.lang.String getMinYear();
  /**
   * <code>string minYear = 4;</code>
   */
  com.google.protobuf.ByteString
      getMinYearBytes();

  /**
   * <code>string staIds = 5;</code>
   */
  java.lang.String getStaIds();
  /**
   * <code>string staIds = 5;</code>
   */
  com.google.protobuf.ByteString
      getStaIdsBytes();

  /**
   * <code>string dataCode = 6;</code>
   */
  java.lang.String getDataCode();
  /**
   * <code>string dataCode = 6;</code>
   */
  com.google.protobuf.ByteString
      getDataCodeBytes();
}
