// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surface.proto

package com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc;

/**
 * Protobuf type {@code surfaceDataSelect.StatSurfTemByMYearRequest}
 */
public final class StatSurfTemByMYearRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:surfaceDataSelect.StatSurfTemByMYearRequest)
        StatSurfTemByMYearRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use StatSurfTemByMYearRequest.newBuilder() to construct.
    private StatSurfTemByMYearRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private StatSurfTemByMYearRequest() {
        elements_ = "";
        minMD_ = "";
        maxMD_ = "";
        minYear_ = "";
        staIds_ = "";
        dataCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private StatSurfTemByMYearRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        elements_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        minMD_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        maxMD_ = s;
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        minYear_ = s;
                        break;
                    }
                    case 42: {
                        java.lang.String s = input.readStringRequireUtf8();

                        staIds_ = s;
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();

                        dataCode_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.class, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.Builder.class);
    }

    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private volatile java.lang.Object elements_;

    /**
     * <code>string elements = 1;</code>
     */
    public java.lang.String getElements() {
        java.lang.Object ref = elements_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            elements_ = s;
            return s;
        }
    }

    /**
     * <code>string elements = 1;</code>
     */
    public com.google.protobuf.ByteString
    getElementsBytes() {
        java.lang.Object ref = elements_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            elements_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MINMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object minMD_;

    /**
     * <code>string minMD = 2;</code>
     */
    public java.lang.String getMinMD() {
        java.lang.Object ref = minMD_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            minMD_ = s;
            return s;
        }
    }

    /**
     * <code>string minMD = 2;</code>
     */
    public com.google.protobuf.ByteString
    getMinMDBytes() {
        java.lang.Object ref = minMD_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            minMD_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MAXMD_FIELD_NUMBER = 3;
    private volatile java.lang.Object maxMD_;

    /**
     * <code>string maxMD = 3;</code>
     */
    public java.lang.String getMaxMD() {
        java.lang.Object ref = maxMD_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            maxMD_ = s;
            return s;
        }
    }

    /**
     * <code>string maxMD = 3;</code>
     */
    public com.google.protobuf.ByteString
    getMaxMDBytes() {
        java.lang.Object ref = maxMD_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            maxMD_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MINYEAR_FIELD_NUMBER = 4;
    private volatile java.lang.Object minYear_;

    /**
     * <code>string minYear = 4;</code>
     */
    public java.lang.String getMinYear() {
        java.lang.Object ref = minYear_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            minYear_ = s;
            return s;
        }
    }

    /**
     * <code>string minYear = 4;</code>
     */
    public com.google.protobuf.ByteString
    getMinYearBytes() {
        java.lang.Object ref = minYear_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            minYear_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int STAIDS_FIELD_NUMBER = 5;
    private volatile java.lang.Object staIds_;

    /**
     * <code>string staIds = 5;</code>
     */
    public java.lang.String getStaIds() {
        java.lang.Object ref = staIds_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            staIds_ = s;
            return s;
        }
    }

    /**
     * <code>string staIds = 5;</code>
     */
    public com.google.protobuf.ByteString
    getStaIdsBytes() {
        java.lang.Object ref = staIds_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            staIds_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int DATACODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object dataCode_;

    /**
     * <code>string dataCode = 6;</code>
     */
    public java.lang.String getDataCode() {
        java.lang.Object ref = dataCode_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dataCode_ = s;
            return s;
        }
    }

    /**
     * <code>string dataCode = 6;</code>
     */
    public com.google.protobuf.ByteString
    getDataCodeBytes() {
        java.lang.Object ref = dataCode_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            dataCode_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getElementsBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, elements_);
        }
        if (!getMinMDBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, minMD_);
        }
        if (!getMaxMDBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, maxMD_);
        }
        if (!getMinYearBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, minYear_);
        }
        if (!getStaIdsBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, staIds_);
        }
        if (!getDataCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dataCode_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getElementsBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, elements_);
        }
        if (!getMinMDBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, minMD_);
        }
        if (!getMaxMDBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, maxMD_);
        }
        if (!getMinYearBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, minYear_);
        }
        if (!getStaIdsBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, staIds_);
        }
        if (!getDataCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dataCode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest)) {
            return super.equals(obj);
        }
        com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest other = (com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest) obj;

        if (!getElements()
                .equals(other.getElements())) return false;
        if (!getMinMD()
                .equals(other.getMinMD())) return false;
        if (!getMaxMD()
                .equals(other.getMaxMD())) return false;
        if (!getMinYear()
                .equals(other.getMinYear())) return false;
        if (!getStaIds()
                .equals(other.getStaIds())) return false;
        if (!getDataCode()
                .equals(other.getDataCode())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ELEMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getElements().hashCode();
        hash = (37 * hash) + MINMD_FIELD_NUMBER;
        hash = (53 * hash) + getMinMD().hashCode();
        hash = (37 * hash) + MAXMD_FIELD_NUMBER;
        hash = (53 * hash) + getMaxMD().hashCode();
        hash = (37 * hash) + MINYEAR_FIELD_NUMBER;
        hash = (53 * hash) + getMinYear().hashCode();
        hash = (37 * hash) + STAIDS_FIELD_NUMBER;
        hash = (53 * hash) + getStaIds().hashCode();
        hash = (37 * hash) + DATACODE_FIELD_NUMBER;
        hash = (53 * hash) + getDataCode().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code surfaceDataSelect.StatSurfTemByMYearRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:surfaceDataSelect.StatSurfTemByMYearRequest)
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.class, com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.Builder.class);
        }

        // Construct using com.rihang.surface.grpc.surfaceSelect.StatSurfTemByMYearRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            elements_ = "";

            minMD_ = "";

            maxMD_ = "";

            minYear_ = "";

            staIds_ = "";

            dataCode_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.SelectProto.internal_static_surfaceDataSelect_StatSurfTemByMYearRequest_descriptor;
        }

        @java.lang.Override
        public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest getDefaultInstanceForType() {
            return com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest build() {
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest buildPartial() {
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest result = new com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest(this);
            result.elements_ = elements_;
            result.minMD_ = minMD_;
            result.maxMD_ = maxMD_;
            result.minYear_ = minYear_;
            result.staIds_ = staIds_;
            result.dataCode_ = dataCode_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest) {
                return mergeFrom((com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest other) {
            if (other == com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest.getDefaultInstance())
                return this;
            if (!other.getElements().isEmpty()) {
                elements_ = other.elements_;
                onChanged();
            }
            if (!other.getMinMD().isEmpty()) {
                minMD_ = other.minMD_;
                onChanged();
            }
            if (!other.getMaxMD().isEmpty()) {
                maxMD_ = other.maxMD_;
                onChanged();
            }
            if (!other.getMinYear().isEmpty()) {
                minYear_ = other.minYear_;
                onChanged();
            }
            if (!other.getStaIds().isEmpty()) {
                staIds_ = other.staIds_;
                onChanged();
            }
            if (!other.getDataCode().isEmpty()) {
                dataCode_ = other.dataCode_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object elements_ = "";

        /**
         * <code>string elements = 1;</code>
         */
        public java.lang.String getElements() {
            java.lang.Object ref = elements_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                elements_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string elements = 1;</code>
         */
        public com.google.protobuf.ByteString
        getElementsBytes() {
            java.lang.Object ref = elements_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                elements_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string elements = 1;</code>
         */
        public Builder setElements(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            elements_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string elements = 1;</code>
         */
        public Builder clearElements() {

            elements_ = getDefaultInstance().getElements();
            onChanged();
            return this;
        }

        /**
         * <code>string elements = 1;</code>
         */
        public Builder setElementsBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            elements_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object minMD_ = "";

        /**
         * <code>string minMD = 2;</code>
         */
        public java.lang.String getMinMD() {
            java.lang.Object ref = minMD_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                minMD_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string minMD = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMinMDBytes() {
            java.lang.Object ref = minMD_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                minMD_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string minMD = 2;</code>
         */
        public Builder setMinMD(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            minMD_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string minMD = 2;</code>
         */
        public Builder clearMinMD() {

            minMD_ = getDefaultInstance().getMinMD();
            onChanged();
            return this;
        }

        /**
         * <code>string minMD = 2;</code>
         */
        public Builder setMinMDBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            minMD_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object maxMD_ = "";

        /**
         * <code>string maxMD = 3;</code>
         */
        public java.lang.String getMaxMD() {
            java.lang.Object ref = maxMD_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                maxMD_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string maxMD = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMaxMDBytes() {
            java.lang.Object ref = maxMD_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                maxMD_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string maxMD = 3;</code>
         */
        public Builder setMaxMD(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            maxMD_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string maxMD = 3;</code>
         */
        public Builder clearMaxMD() {

            maxMD_ = getDefaultInstance().getMaxMD();
            onChanged();
            return this;
        }

        /**
         * <code>string maxMD = 3;</code>
         */
        public Builder setMaxMDBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            maxMD_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object minYear_ = "";

        /**
         * <code>string minYear = 4;</code>
         */
        public java.lang.String getMinYear() {
            java.lang.Object ref = minYear_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                minYear_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string minYear = 4;</code>
         */
        public com.google.protobuf.ByteString
        getMinYearBytes() {
            java.lang.Object ref = minYear_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                minYear_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string minYear = 4;</code>
         */
        public Builder setMinYear(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            minYear_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string minYear = 4;</code>
         */
        public Builder clearMinYear() {

            minYear_ = getDefaultInstance().getMinYear();
            onChanged();
            return this;
        }

        /**
         * <code>string minYear = 4;</code>
         */
        public Builder setMinYearBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            minYear_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object staIds_ = "";

        /**
         * <code>string staIds = 5;</code>
         */
        public java.lang.String getStaIds() {
            java.lang.Object ref = staIds_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                staIds_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string staIds = 5;</code>
         */
        public com.google.protobuf.ByteString
        getStaIdsBytes() {
            java.lang.Object ref = staIds_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                staIds_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string staIds = 5;</code>
         */
        public Builder setStaIds(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            staIds_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string staIds = 5;</code>
         */
        public Builder clearStaIds() {

            staIds_ = getDefaultInstance().getStaIds();
            onChanged();
            return this;
        }

        /**
         * <code>string staIds = 5;</code>
         */
        public Builder setStaIdsBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            staIds_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object dataCode_ = "";

        /**
         * <code>string dataCode = 6;</code>
         */
        public java.lang.String getDataCode() {
            java.lang.Object ref = dataCode_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataCode_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string dataCode = 6;</code>
         */
        public com.google.protobuf.ByteString
        getDataCodeBytes() {
            java.lang.Object ref = dataCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dataCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string dataCode = 6;</code>
         */
        public Builder setDataCode(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            dataCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string dataCode = 6;</code>
         */
        public Builder clearDataCode() {

            dataCode_ = getDefaultInstance().getDataCode();
            onChanged();
            return this;
        }

        /**
         * <code>string dataCode = 6;</code>
         */
        public Builder setDataCodeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            dataCode_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:surfaceDataSelect.StatSurfTemByMYearRequest)
    }

    // @@protoc_insertion_point(class_scope:surfaceDataSelect.StatSurfTemByMYearRequest)
    private static final com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest();
    }

    public static com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatSurfTemByMYearRequest>
            PARSER = new com.google.protobuf.AbstractParser<StatSurfTemByMYearRequest>() {
        @java.lang.Override
        public StatSurfTemByMYearRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new StatSurfTemByMYearRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<StatSurfTemByMYearRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatSurfTemByMYearRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.hw.hwcdp3.dc.project.beijing.sourcedataget.sueface.grpc.StatSurfTemByMYearRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

